name: Release

# yamllint disable rule:line-length
# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manually enter tag'
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # Grabs the release tag, OR falls back to the manual input tag if the release tag is null
      - name: Get Version
        id: get_version
        run: echo "VERSION=${{ github.event.release.tag_name || inputs.tags }}" >> "$GITHUB_ENV"

      # Updates the files with the unified VERSION variable
      - name: Set version number
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ env.VERSION }}"' ${{ github.workspace }}/custom_components/keymaster/const.py
          sed -i '/version/c\  \"version\": \"${{ env.VERSION }}\"' ${{ github.workspace }}/custom_components/keymaster/manifest.json

      # Pack the keymaster dir as a zip
      - name: ZIP Keymaster Dir
        run: |
          cd ${{ github.workspace }}/custom_components/keymaster
          zip keymaster.zip -r ./

      # Upload to the release using the unified VERSION variable
      - name: ðŸ“¤ Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/keymaster/keymaster.zip
          tag_name: ${{ env.VERSION }}
