name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: ðŸ”¢ Get version
        if: ${{ github.event_name == 'release' }}
        id: version
        uses: home-assistant/actions/helpers/version@master
      - name: ðŸ”¢ Set version number
        if: ${{ github.event_name == 'release' }}
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ steps.get_version.outputs.VERSION }}"' ${{ github.workspace }}/custom_components/keymaster/const.py
          sed -i '/version/c\  \"version\": \"${{ steps.get_version.outputs.VERSION }}\"' ${{ github.workspace }}/custom_components/keymaster/manifest.json
      # Pack the keymaster dir as a zip and upload to the release
      - name: ZIP Keymaster Dir
        run: |
          cd ${{ github.workspace }}/custom_components/keymaster
          zip keymaster.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/keymaster/keymaster.zip
          asset_name: keymaster.zip
          tag: ${{ github.ref }}
          overwrite: true
