name: Update Manifest

on:
  push:
  pull_request:

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: "Set version numbmer"
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ github.ref }}"' /home/runner/work/keymaster/keymaster/custom_components/keymaster/const.py

      - name: Update mainifest.json
        run: |
          sed -i '/version/c\     \"version\" : \"$VERSION\",' /home/runner/work/keymaster/manifest.json
        env:
          VERSION: ${{ github.ref }}

      - name: Commit files
        run: |
          if [ $(git diff HEAD | wc -l) -gt 30 ]
          then
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git commit -a --amend --no-edit || true
          git push --force || true
          fi
